function packageJsonFor(project, ui) {
  const dependencies = { next: 'latest', react: 'latest', 'react-dom': 'latest', '@supabase/ssr': 'latest', '@supabase/supabase-js': 'latest' };
  const devDependencies = { typescript: 'latest', '@types/node': 'latest', '@types/react': 'latest', '@types/react-dom': 'latest' };
  if (ui === 'shadcn' || ui === 'tailwind') {
    dependencies.tailwindcss = 'latest';
    devDependencies['@tailwindcss/postcss'] = 'latest';
  }
  if (ui === 'shadcn') {
    dependencies.clsx = 'latest';
    dependencies['tailwind-merge'] = 'latest';
    dependencies['class-variance-authority'] = 'latest';
  }
  return JSON.stringify({ name: project, private: true, scripts: { dev: 'next dev', build: 'next build', start: 'next start', lint: 'next lint', verify: 'next build' }, dependencies, devDependencies }, null, 2) + '\n';
}

export function buildFiles(project, ui, version = '0.1.0', { supabasePorts } = {}) {
  const usesTailwind = ui === 'shadcn' || ui === 'tailwind';
  const ports = supabasePorts ?? { api: 54321, db: 54322, studio: 54323, mail: 54324, analytics: 54327, shadow: 54320 };
  const projectId = project.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'foundry-app';
  const button = ui === 'shadcn' ? `import { cn } from '@/lib/utils';

type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

export function Button({ className, children, ...props }: ButtonProps) {
  return <button className={cn('rounded border px-3 py-2 text-sm', className)} {...props}>{children}</button>;
}
` : usesTailwind ? `type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

export function Button({ children, ...props }: ButtonProps) {
  return <button className="rounded border px-3 py-2 text-sm" {...props}>{children}</button>;
}
` : `type ButtonProps = React.ButtonHTMLAttributes<HTMLButtonElement>;

export function Button({ children, ...props }: ButtonProps) {
  return <button {...props}>{children}</button>;
}
`;
  const input = ui === 'shadcn' ? `import { cn } from '@/lib/utils';

type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

export function Input({ className, ...props }: InputProps) {
  return <input className={cn('rounded border px-3 py-2', className)} {...props} />;
}
` : usesTailwind ? `type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

export function Input(props: InputProps) {
  return <input className="rounded border px-3 py-2" {...props} />;
}
` : `type InputProps = React.InputHTMLAttributes<HTMLInputElement>;

export function Input(props: InputProps) {
  return <input {...props} />;
}
`;
  const styles = usesTailwind ? '@import "tailwindcss";\n\n:root { color-scheme: light; }\n' : ':root { color-scheme: light; font-family: system-ui, sans-serif; }\n\nbody { margin: 0; }\n\nmain { max-width: 960px; margin: 0 auto; padding: 2rem; }\n\nform { display: grid; gap: 1rem; max-width: 24rem; margin: 4rem auto; }\n\nlabel { display: grid; gap: 0.35rem; }\n';
  const fieldClass = usesTailwind ? ' className="grid gap-1"' : '';
  const formClass = usesTailwind ? ' className="grid max-w-sm gap-4"' : '';
  const pageClass = usesTailwind ? ' className="mx-auto max-w-5xl p-8"' : '';
  const titleClass = usesTailwind ? ' className="text-2xl font-semibold tracking-tight"' : '';
  const mutedClass = usesTailwind ? ' className="mt-2 text-sm text-slate-600"' : '';
  const manifest = `schema: papergio/v1\n\nproject:\n  name: ${project}\n  type: saas\n\nfoundation:\n  tool: foundry\n  version: ${version}\n  preset: saas\n  preset_version: ${version}\n\nstack:\n  frontend: nextjs\n  backend: nextjs\n  database: supabase\n  deploy: vercel\n  repository: git\n\nui:\n  provider: ${ui}\n  tailwind: ${usesTailwind}\n  style: neutral\n\nmodules:\n  auth: true\n  database: true\n  migrations: true\n  admin: true\n  billing: false\n\nagent:\n  context_file: AGENTS.md\n  verify_command: npm run verify\n\nnext_steps:\n  install: npm install\n  dev: npm run dev\n  verify: npm run verify\n`;
  const publicManifest = manifest.replace('  tool: foundry\\n', '  tool: papergio\\n  classifier: foundry\\n');
  const files = {
    'package.json': packageJsonFor(project, ui),
    '.env.example': 'NEXT_PUBLIC_SUPABASE_URL=\nNEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=\n',
    '.gitignore': 'node_modules\n.next\n.env\n.env.local\n.foundry\n',
    'README.md': `# ${project}\n\nGenerated by Papergio using Foundry and the SaaS preset.\n\n## Project metadata\n\n- Canonical manifest: [papergio.yaml](./papergio.yaml)\n- Foundry compatibility manifest: [foundry.yaml](./foundry.yaml)\n- Agent instructions: [AGENTS.md](./AGENTS.md)\n\n` +
      `## Local development\n\n1. Copy .env.example to .env.local and add Supabase credentials.\n2. Run npm install.\n3. Run npm run dev.\n\nRun npm run verify to validate the production build.\n`,
    'AGENTS.md': `# AGENTS.md\n\n## Project\n\nThis is a minimal Next.js SaaS foundation generated by Papergio and Foundry.\n\n## Project metadata\n\n- Read papergio.yaml first. It is the canonical Papergio project manifest.\n- foundry.yaml is kept as a compatibility copy for older Foundry tooling. Do not edit the manifests independently.\n\n## Where to work\n\n- Add product functionality under src/features.\n- Add product routes under src/app/(app).\n- Add database changes as Supabase migrations.\n- Keep auth, permissions, and integration helpers reusable.\n\n## Rules\n\n- Keep secrets in .env.local; never commit them.\n- Validate authorization on the server.\n- Run npm run verify before completing a feature.\n- Keep the generated UI neutral and replaceable.\n\n## Stack\n\n- Next.js with TypeScript\n- Supabase Auth and PostgreSQL\n- Vercel deployment\n- Git with GitHub Actions\n`,
    'papergio.yaml': publicManifest,
    'foundry.yaml': publicManifest,
    'tsconfig.json': JSON.stringify({ compilerOptions: { target: 'ES2017', lib: ['dom', 'dom.iterable', 'esnext'], allowJs: false, skipLibCheck: true, strict: true, noEmit: true, esModuleInterop: true, module: 'esnext', moduleResolution: 'bundler', resolveJsonModule: true, isolatedModules: true, jsx: 'react-jsx', incremental: true, paths: { '@/*': ['./src/*'] }, plugins: [{ name: 'next' }] }, include: ['next-env.d.ts', '.next/types/**/*.ts', '.next/dev/types/**/*.ts', '**/*.ts', '**/*.tsx'], exclude: ['node_modules'] }, null, 2) + '\n',
    'next-env.d.ts': '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// NOTE: This file should not be edited\n',
    'next.config.ts': 'import type { NextConfig } from "next";\n\nconst nextConfig: NextConfig = {};\nexport default nextConfig;\n',
    ...(ui === 'shadcn' ? {
      'components.json': JSON.stringify({ '$schema': 'https://ui.shadcn.com/schema.json', style: 'new-york', rsc: true, tsx: true, tailwind: { config: '', css: 'src/app/globals.css', baseColor: 'slate', cssVariables: true, prefix: '' }, aliases: { components: '@/components', utils: '@/lib/utils', ui: '@/components/ui', lib: '@/lib', hooks: '@/hooks' } }, null, 2) + '\n',
      'src/lib/utils.ts': `import { type ClassValue, clsx } from 'clsx';\nimport { twMerge } from 'tailwind-merge';\n\nexport function cn(...inputs: ClassValue[]) {\n  return twMerge(clsx(inputs));\n}\n`,
    } : {}),
    'src/app/globals.css': styles,
    ...(usesTailwind ? { 'postcss.config.mjs': `const config = {\n  plugins: {\n    "@tailwindcss/postcss": {},\n  },\n};\n\nexport default config;\n` } : {}),
    'src/app/layout.tsx': `import type { Metadata } from "next";\nimport "./globals.css";\n\nexport const metadata: Metadata = { title: "${project}" };\n\nexport default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return <html lang="en"><body>{children}</body></html>;\n}\n`,
    'src/app/page.tsx': `import Link from 'next/link';\n\nexport default function LandingPage() {\n  return <main${pageClass}><h1${titleClass}>${project}</h1><p${mutedClass}>A neutral SaaS foundation generated by Foundry.</p><p><Link href="/login">Sign in</Link> · <Link href="/signup">Create account</Link></p></main>;\n}\n`,
    'src/app/(auth)/layout.tsx': `export default function AuthLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return <main>${usesTailwind ? '<div className="mx-auto max-w-sm">{children}</div>' : '{children}'}</main>;\n}\n`,
    'src/app/(auth)/login/page.tsx': `import Link from 'next/link';\nimport { LoginForm } from '@/components/auth/login-form';\n\nexport default function LoginPage() {\n  return <><h1>Sign in</h1><LoginForm /><p><Link href="/signup">Create account</Link></p></>;\n}\n`,
    'src/app/(auth)/signup/page.tsx': `import Link from 'next/link';\nimport { SignupForm } from '@/components/auth/signup-form';\n\nexport default function SignupPage() {\n  return <><h1>Create account</h1><SignupForm /><p><Link href="/login">I already have an account</Link></p></>;\n}\n`,
    'src/app/(app)/layout.tsx': `import Link from 'next/link';\n\nexport default function AppLayout({ children }: Readonly<{ children: React.ReactNode }>) {\n  return <main${pageClass}><nav><Link href="/dashboard">Dashboard</Link> · <Link href="/settings">Settings</Link></nav>{children}</main>;\n}\n`,
    'src/app/(app)/dashboard/page.tsx': `import { LogoutButton } from '@/components/auth/logout-button';\nimport { requireUser } from '@/lib/auth/require-user';\n\nexport default async function DashboardPage() {\n  const { user } = await requireUser();\n  return <section><h1>Dashboard</h1><p>Authenticated workspace ready for your product.</p><p>{user.email}</p><LogoutButton /></section>;\n}\n`,
    'src/app/(app)/settings/page.tsx': `import { requireUser } from '@/lib/auth/require-user';\n\nexport default async function SettingsPage() {\n  await requireUser();\n  return <section><h1>Settings</h1><p>Account preferences.</p></section>;\n}\n`,
    'src/app/admin/page.tsx': `import { requireAdmin } from '@/lib/permissions/require-admin';\n\nexport default async function AdminPage() {\n  await requireAdmin();\n  return <main${pageClass}><h1>Admin</h1><p>Minimal admin area.</p></main>;\n}\n`,
    'src/app/unauthorized/page.tsx': `import Link from 'next/link';\n\nexport default function UnauthorizedPage() {\n  return <main${pageClass}><h1>Access denied</h1><p>You do not have permission to access this area.</p><Link href="/dashboard">Back to dashboard</Link></main>;\n}\n`,
    'src/components/ui/button.tsx': button,
    'src/components/ui/input.tsx': input,
    'src/components/auth/login-form.tsx': `'use client';\n\nimport { FormEvent, useState } from 'react';\nimport { createClient } from '@/lib/supabase/client';\nimport { Button } from '@/components/ui/button';\nimport { Input } from '@/components/ui/input';\n\nexport function LoginForm() {\n  const [error, setError] = useState('');\n  const [loading, setLoading] = useState(false);\n  async function submit(event: FormEvent<HTMLFormElement>) {\n    event.preventDefault(); setLoading(true); setError('');\n    const form = new FormData(event.currentTarget);\n    const { error: authError } = await createClient().auth.signInWithPassword({ email: String(form.get('email')), password: String(form.get('password')) });\n    if (authError) setError(authError.message); else window.location.href = '/dashboard';\n    setLoading(false);\n  }\n  return <form onSubmit={submit}${formClass}><label${fieldClass}>E-mail<Input name="email" type="email" required /></label><label${fieldClass}>Senha<Input name="password" type="password" required /></label><Button disabled={loading}>{loading ? 'Entrando...' : 'Entrar'}</Button>{error && <p role="alert">{error}</p>}</form>;\n}\n`,
    'src/components/auth/signup-form.tsx': `'use client';\n\nimport { FormEvent, useState } from 'react';\nimport { createClient } from '@/lib/supabase/client';\nimport { Button } from '@/components/ui/button';\nimport { Input } from '@/components/ui/input';\n\nexport function SignupForm() {\n  const [error, setError] = useState('');\n  const [loading, setLoading] = useState(false);\n  async function submit(event: FormEvent<HTMLFormElement>) {\n    event.preventDefault(); setLoading(true); setError('');\n    const form = new FormData(event.currentTarget);\n    const { error: authError } = await createClient().auth.signUp({ email: String(form.get('email')), password: String(form.get('password')) });\n    if (authError) setError(authError.message); else window.location.href = '/dashboard';\n    setLoading(false);\n  }\n  return <form onSubmit={submit}${formClass}><label${fieldClass}>E-mail<Input name="email" type="email" required /></label><label${fieldClass}>Senha<Input name="password" type="password" minLength={8} required /></label><Button disabled={loading}>{loading ? 'Criando...' : 'Criar conta'}</Button>{error && <p role="alert">{error}</p>}</form>;\n}\n`,
    'src/components/auth/signup-form.tsx': `'use client';\n\nimport { FormEvent, useState } from 'react';\nimport { createClient } from '@/lib/supabase/client';\nimport { Button } from '@/components/ui/button';\nimport { Input } from '@/components/ui/input';\n\nexport function SignupForm() {\n  const [error, setError] = useState('');\n  const [loading, setLoading] = useState(false);\n  async function submit(event: FormEvent<HTMLFormElement>) {\n    event.preventDefault(); setLoading(true); setError('');\n    const form = new FormData(event.currentTarget);\n    const { data, error: authError } = await createClient().auth.signUp({ email: String(form.get('email')), password: String(form.get('password')) });\n    if (authError) setError(authError.message); else window.location.href = data.session ? '/dashboard' : '/login';\n    setLoading(false);\n  }\n  return <form onSubmit={submit}${formClass}><label${fieldClass}>E-mail<Input name="email" type="email" required /></label><label${fieldClass}>Senha<Input name="password" type="password" minLength={8} required /></label><Button disabled={loading}>{loading ? 'Criando...' : 'Criar conta'}</Button>{error && <p role="alert">{error}</p>}</form>;\n}\n`,
    'src/components/auth/logout-button.tsx': `'use client';\n\nimport { useState } from 'react';\nimport { createClient } from '@/lib/supabase/client';\nimport { Button } from '@/components/ui/button';\n\nexport function LogoutButton() {\n  const [loading, setLoading] = useState(false);\n  async function logout() {\n    setLoading(true); await createClient().auth.signOut(); window.location.href = '/';\n  }\n  return <Button onClick={logout} disabled={loading}>{loading ? 'Saindo...' : 'Sair'}</Button>;\n}\n`,
    'src/lib/supabase/client.ts': `import { createBrowserClient } from '@supabase/ssr';\n\nexport function createClient() {\n  return createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);\n}\n`,
    'src/lib/supabase/server.ts': `import { createServerClient } from '@supabase/ssr';\nimport { cookies } from 'next/headers';\n\nexport async function createClient() {\n  const cookieStore = await cookies();\n  return createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, {\n    cookies: {\n      getAll() { return cookieStore.getAll(); },\n      setAll(cookiesToSet) {\n        try { cookiesToSet.forEach(({ name, value, options }) => cookieStore.set(name, value, options)); } catch { /* Server Components cannot write cookies. */ }\n      }\n    }\n  });\n}\n`,
    'src/lib/auth/require-user.ts': `import { redirect } from 'next/navigation';\nimport { createClient } from '@/lib/supabase/server';\n\nexport async function requireUser() {\n  const client = await createClient();\n  const { data: { user } } = await client.auth.getUser();\n  if (!user) redirect('/login');\n  return { client, user };\n}\n`,
    'src/lib/permissions/require-admin.ts': `import { redirect } from 'next/navigation';\nimport { requireUser } from '@/lib/auth/require-user';\n\nexport async function requireAdmin() {\n  const { client, user } = await requireUser();\n  const { data: profile } = await client.from('profiles').select('role').eq('id', user.id).single();\n  if (profile?.role !== 'admin') redirect('/unauthorized');\n  return { client, user, profile };\n}\n`,
    'src/proxy.ts': `import { createServerClient } from '@supabase/ssr';\nimport { type NextRequest, NextResponse } from 'next/server';\n\nexport async function proxy(request: NextRequest) {\n  let response = NextResponse.next({ request });\n  const supabase = createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, {\n    cookies: {\n      getAll() { return request.cookies.getAll(); },\n      setAll(cookiesToSet) {\n        cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));\n        response = NextResponse.next({ request });\n        cookiesToSet.forEach(({ name, value, options }) => response.cookies.set(name, value, options));\n      }\n    }\n  });\n  const { data: { user } } = await supabase.auth.getUser();\n  const pathname = request.nextUrl.pathname;\n  const protectedRoute = ['/dashboard', '/settings', '/admin'].some((route) => pathname === route || pathname.startsWith(route + '/'));\n  const authRoute = pathname === '/login' || pathname === '/signup';\n  if (!user && protectedRoute) {\n    const url = request.nextUrl.clone(); url.pathname = '/login'; url.searchParams.set('redirectedFrom', pathname); return NextResponse.redirect(url);\n  }\n  if (user && authRoute) {\n    const url = request.nextUrl.clone(); url.pathname = '/dashboard'; return NextResponse.redirect(url);\n  }\n  return response;\n}\n\nexport const config = { matcher: ['/((?!_next/static|_next/image|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)'] };\n`,
    'src/features/.gitkeep': '',
    'supabase/config.toml': `project_id = "${projectId}"\n\n[api]\nenabled = true\nport = ${ports.api}\n\n[db]\nport = ${ports.db}\nshadow_port = ${ports.shadow}\n\n[studio]\nenabled = true\nport = ${ports.studio}\n\n[local_smtp]\nenabled = true\nport = ${ports.mail}\n\n[analytics]\nenabled = true\nport = ${ports.analytics}\n`,
    'supabase/migrations/20260817000000_initial.sql': `-- Initial profile and authorization foundation.\n\ncreate table if not exists public.profiles (\n  id uuid primary key references auth.users(id) on delete cascade,\n  role text not null default 'user' check (role in ('user', 'admin')),\n  created_at timestamptz not null default now()\n);\n\nalter table public.profiles enable row level security;\n\ncreate policy "Profiles are viewable by the owner" on public.profiles for select using (auth.uid() = id);\ncreate policy "Profiles are editable by the owner" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);\n\ncreate or replace function public.prevent_profile_role_change()\nreturns trigger\nlanguage plpgsql\nsecurity definer set search_path = public\nas $$\nbegin\n  if new.role is distinct from old.role and coalesce(auth.role(), '') <> 'service_role' then\n    raise exception 'Only service role can change profile roles';\n  end if;\n  return new;\nend;\n$$;\n\ncreate or replace trigger protect_profile_role\n  before update on public.profiles\n  for each row execute procedure public.prevent_profile_role_change();\n\ncreate or replace function public.handle_new_user()\nreturns trigger\nlanguage plpgsql\nsecurity definer set search_path = public\nas $$\nbegin\n  insert into public.profiles (id) values (new.id);\n  return new;\nend;\n$$;\n\ncreate or replace trigger on_auth_user_created\n  after insert on auth.users\n  for each row execute procedure public.handle_new_user();\n`,
    '.github/workflows/ci.yml': `name: CI\n\non:\n  push:\n    branches: [main]\n  pull_request:\n\njobs:\n  verify:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: npm\n      - run: npm ci\n      - run: npm run verify\n`,
    'vercel.json': JSON.stringify({ framework: 'nextjs' }, null, 2) + '\n'
  };

  const englishReplacements = new Map([
    ['Entrar', 'Sign in'],
    ['Criar conta', 'Create account'],
    ['Já tenho uma conta', 'I already have an account'],
    ['Configurações', 'Settings'],
    ['Área autenticada pronta para receber o produto.', 'Authenticated workspace ready for your product.'],
    ['Preferências da conta.', 'Account preferences.'],
    ['Área administrativa mínima.', 'Minimal admin area.'],
    ['Acesso negado', 'Access denied'],
    ['Você não possui permissão para acessar esta área.', 'You do not have permission to access this area.'],
    ['Voltar ao dashboard', 'Back to dashboard'],
    ['E-mail', 'Email'],
    ['Senha', 'Password'],
    ['Entrando...', 'Signing in...'],
    ['Criando...', 'Creating...'],
    ['Saindo...', 'Signing out...'],
    ['Sair', 'Sign out']
  ]);
  return Object.fromEntries(Object.entries(files).map(([file, contents]) => [file, typeof contents === 'string' ? [...englishReplacements].reduce((output, [from, to]) => output.replaceAll(from, to), contents) : contents]));
}
